import { prisma } from '@/lib/db';
import { getSession } from '@/lib/session';
import { can } from '@/lib/rbac';
import { platformName, COMPLIANCE_TIERS } from '@/lib/constants';
import { TierBadge, Fold } from '@/components/ui';
import { Icon } from '@/components/icons';
import { Checker } from './Checker';
import { WordManager } from './WordManager';
import { FeedbackPanel } from './FeedbackPanel';
import type { CustomWord } from './actions';
import { MakeTabs } from '@/components/MakeTabs';
import { HubHeader } from '@/components/HubHeader';
import { getServerLang } from '@/lib/i18n/server';
import { getDictionary } from '@/lib/i18n/dict';

export const dynamic = 'force-dynamic';

const TIER_ORDER = ['legal', 'platform', 'industry', 'custom'] as const;

const COMPLIANCE_TIER_I18N: Record<string, { nameEn: string; descEn: string }> = {
  legal: { nameEn: 'Legal Tier', descEn: 'Statutory redlines (Ad Law, AIGC rules)' },
  platform: { nameEn: 'Platform Tier', descEn: 'Platform community guidelines' },
  industry: { nameEn: 'Industry Tier', descEn: 'High-risk sectors (medical, financial)' },
  custom: { nameEn: 'Custom Tier', descEn: 'Tenant custom blocklist & allowlist' },
  semantic: { nameEn: 'Semantic Tier', descEn: 'AI semantic analysis findings' },
};

export default async function CompliancePage() {
  const s = await getSession();
  const lang = await getServerLang();
  const dict = getDictionary(lang);

  // 可见词库：全局三级（legal/platform/industry）+ 本租户自定义级
  const [words, recentDrafts, feedbackItems] = await Promise.all([
    prisma.sensitiveWord.findMany({
      where: {
        OR: [
          { tenantId: null, enabled: true },
          { tenantId: s.tenantId },
        ],
      },
      orderBy: { createdAt: 'asc' },
    }),
    prisma.draft.findMany({
      where: { account: { workspaceId: s.workspaceId } },
      orderBy: { updatedAt: 'desc' },
      take: 10,
      include: { versions: { orderBy: { seq: 'desc' }, take: 1 } },
    }),
    prisma.complianceFeedback.findMany({
      where: { tenantId: s.tenantId },
      orderBy: { createdAt: 'desc' },
      take: 20,
    }),
  ]);

  const draftOptions = recentDrafts.map((d) => ({
    id: d.id,
    title: d.title,
    content: d.versions[0]?.content || d.title,
  }));

  const customWords: CustomWord[] = (words.filter((w) => w.tier === 'custom')).map((w) => ({
    id: w.id,
    word: w.word,
    action: w.action,
    platform: w.platform,
    suggestion: w.suggestion,
    enabled: w.enabled,
    createdAt: w.createdAt.toISOString(),
  }));

  const byTier = new Map<string, typeof words>();
  for (const w of words) {
    if (!byTier.has(w.tier)) byTier.set(w.tier, []);
    byTier.get(w.tier)!.push(w);
  }

  return (
    <>
      <HubHeader
        title={dict.tabs.makeTitle}
        tabs={<MakeTabs active="check" inline />}
      />

      <div className="risk-legend">
        <span className="risk-chip">
          <b>{byTier.get('legal')?.length ?? 176}</b> {lang === 'en' ? 'Legal Redlines' : '法律红线'}
        </span>
        <span className="risk-chip">
          <b>{byTier.get('platform')?.length ?? 180}</b> {lang === 'en' ? 'Platform Rules' : '平台规范'}
        </span>
        <span className="risk-chip">
          <b>{byTier.get('industry')?.length ?? 85}</b> {lang === 'en' ? 'Industry Rules' : '行业规则'}
        </span>
        <span className="risk-chip">
          <b>{byTier.get('custom')?.length ?? 0}</b> {lang === 'en' ? 'Custom' : '自定义'}
        </span>
      </div>

      {/* 实时检测工作台（原型两栏网格） */}
      <Checker drafts={draftOptions} canCheck={can(s.role, 'compliance.check')} />

      {/* AIGC 标识义务提醒 */}
      <div className="alert-gradient-brand" style={{ padding: '14px 18px', marginBottom: 16 }}>
        <div className="row" style={{ gap: 12, alignItems: 'flex-start' }}>
          <div className="icon-box-brand">
            <Icon.shield size={18} />
          </div>
          <div>
            <b className="small" style={{ color: 'var(--brand)', fontSize: 13.5 }}>
              {lang === 'en' ? 'AIGC Labeling Obligation Reminder (CAC Regulatory Standard)' : 'AIGC 标识义务提醒（国家网信办新规）'}
            </b>
            <div className="small" style={{ marginTop: 2, opacity: 0.9, lineHeight: 1.6 }}>
              {lang === 'en'
                ? 'Under the "Measures for the Labeling of AI-Generated Synthesized Content", AI-generated or synthetic content must prominently state "This content is generated by AI" and retain necessary implicit metadata labels. Before publishing AI-assisted images, text, or video, please include declarations in copy or watermarks.'
                : '依据《人工智能生成合成内容标识办法》，AI 生成或合成的内容需显著声明「本内容由 AI 生成」，并保留必要的隐式元数据标识。发布 AI 参与创作的图文／视频前，请在正文或水印处加注声明。'}
            </div>
          </div>
        </div>
      </div>

      {/* 词库总览、自定义词库、误报反馈、合规说明（响应式并排收纳） */}
      <div className="fold-row" style={{ marginBottom: 20 }}>
        <Fold
          title={lang === 'en' ? '4-Tier Lexicon' : '四级词库总览'}
          sub={lang === 'en' ? 'Tiers and coverage rules' : '共几级、各拦什么'}
          note={<span className="small muted">{lang === 'en' ? 'Reference' : '看一次就够'}</span>}
        >
          <div className="stack" style={{ gap: 16 }}>
            {TIER_ORDER.map((tier) => {
              const list = byTier.get(tier) ?? [];
              const t = COMPLIANCE_TIERS[tier];
              const tEn = COMPLIANCE_TIER_I18N[tier];
              return (
                <div key={tier}>
                  <div className="row-between" style={{ marginBottom: 8 }}>
                    <div className="row" style={{ gap: 8 }}>
                      <TierBadge tier={tier} lang={lang} />
                      <span className="small muted">{lang === 'en' ? (tEn?.descEn ?? t.desc) : t.desc}</span>
                    </div>
                    <span className="badge badge-gray">{list.length} {lang === 'en' ? 'items' : '条'}</span>
                  </div>
                  {list.length === 0 ? (
                    <div className="small muted">{lang === 'en' ? 'No entries' : '暂无词条'}</div>
                  ) : (
                    <div className="stack" style={{ gap: 6 }}>
                      {list.slice(0, 4).map((w) => (
                        <div key={w.id} className="list-row" style={{ alignItems: 'center' }}>
                          <span className="mono" style={{ minWidth: 84, fontWeight: 600 }}>{w.word}</span>
                          <span className={`badge ${w.action === 'block' ? 'badge-red' : w.action === 'warn' ? 'badge-amber' : 'badge-brand'}`}>
                            {w.action === 'block' ? (lang === 'en' ? 'Block' : '禁用') : w.action === 'warn' ? (lang === 'en' ? 'Warn' : '警告') : (lang === 'en' ? 'Suggest' : '建议')}
                          </span>
                          <span className="small muted" style={{ flex: 1 }}>
                            {w.platform ? `${platformName(w.platform, lang)} · ` : ''}
                            {w.suggestion ? `${lang === 'en' ? 'Replace with ' : '改为 '}${w.suggestion}` : (w.category ?? '')}
                          </span>
                        </div>
                      ))}
                      {list.length > 4 && <div className="small muted">…{lang === 'en' ? `plus ${list.length - 4} more` : `另有 ${list.length - 4} 条`}</div>}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </Fold>

        <Fold
          title={lang === 'en' ? 'Custom Lexicon' : '自定义词库管理'}
          sub={lang === 'en' ? 'Add blacklist terms or whitelist replacement suggestions' : '添加黑名单词条或白名单替代建议'}
          note={<span className="small muted">{lang === 'en' ? 'Expand to add' : '要加词才翻开'}</span>}
        >
          <WordManager words={customWords} />
        </Fold>

        <Fold
          title={lang === 'en' ? 'False Positive Feedback' : '误报反馈'}
          sub={lang === 'en' ? 'Believe a term is a false positive in your context? Let us know' : '语境误报申诉'}
          note={<span className="small muted">{lang === 'en' ? 'Occasional' : '偶尔用'}</span>}
        >
          <FeedbackPanel items={feedbackItems.map((f) => ({
            id: f.id,
            word: f.word,
            tier: f.tier,
            context: f.context,
            reason: f.reason,
            status: f.status,
            createdAt: f.createdAt.toISOString(),
          }))} canResolve={can(s.role, 'compliance.resolve')} />
        </Fold>

        <Fold
          title={lang === 'en' ? 'Compliance Guide' : '合规说明'}
          sub={lang === 'en' ? 'Must-read before publishing' : '发布前必读'}
          note={<span className="small muted">{lang === 'en' ? 'Reference' : '看一次就够'}</span>}
        >
          <div className="stack" style={{ gap: 12 }}>
            <div className="row" style={{ gap: 10, alignItems: 'flex-start' }}>
              <span style={{ color: 'var(--brand)', marginTop: 2 }}><Icon.bulb size={16} /></span>
              <div>
                <b className="small">{lang === 'en' ? 'Lexicon Instant Match + AI Semantic Recheck' : '词库秒查 + AI 语义二次复核'}</b>
                <div className="small muted" style={{ marginTop: 3 }}>
                  {lang === 'en' ? (
                    <>
                      Two-step check: First run server-side lexicon matching (millisecond speed, zero model cost, no billing), then send copy to AI for semantic review to detect unlisted variants and implicit claims.{' '}
                      <b>Your pasted text will leave the browser</b>—it is sent to Beacon server, and in step 2 sent to the model provider. Inspection records are persisted only when <b>linked to a draft and actual violations are hit</b> (for "what was blocked last week" audits). Temporary scratchpad text is never stored in DB. Statutory legal redlines block one-click export and must be rewritten first.{' '}
                      <b>Boundary note:</b> This tool provides pre-publication self-checks, not a substitute for platform moderation or legal counsel. Variant evasions (pinyin/homophones/split characters) may escape detection.
                    </>
                  ) : (
                    <>
                      检测分两步：先在<b>服务端</b>跑词库匹配（毫秒级、不调用模型、不计费），
                      再把文案送一次 AI 做语义复核，找词库覆盖不到的变体与隐含承诺。
                      <b>你贴进来的文案会离开浏览器</b>——它会发到烽火台服务器，并在第二步随请求发给模型服务商。
                      检测记录只有在<b>关联了草稿且确实命中</b>时才会留存（用于「上周被拦了什么」），
                      检测框里的临时文本不入库。
                      法律级红线命中即禁止导出，需先改写规避。
                      <b>边界说明：</b>本工具做的是发布前自查，不替代平台审核，也不构成法律意见；变体规避写法（拼音/谐音/拆字）可能漏检。
                    </>
                  )}
                </div>
              </div>
            </div>
            <div className="divider" />
            <div className="row" style={{ gap: 10, alignItems: 'flex-start' }}>
              <span style={{ color: 'var(--brand)', marginTop: 2 }}><Icon.chat size={16} /></span>
              <div>
                <b className="small">{lang === 'en' ? 'False Positives Can Be Reported' : '误报可反馈'}</b>
                <div className="small muted" style={{ marginTop: 3 }}>
                  {lang === 'en'
                    ? 'The rulebook leans conservative. If a word is a false positive in your industry context, you can whitelist or adjust its action in the "Custom Tier", or submit feedback. Rules are continuously updated with platform policies.'
                    : '词库为宁可错杀的保守策略，若某词在你的语境下属误报，可在「自定义级」加入白名单或调整动作等级，词库会按平台规则版本持续更新。'}
                </div>
              </div>
            </div>
          </div>
        </Fold>
      </div>
    </>
  );
}
