/**
 * 中国 34 个省级行政区、地级市及区县的标准嵌套 Schema.org areaServed 图谱。
 * 符合 Schema.org Country -> AdministrativeArea / City 标准格式。
 */

export interface SchemaGeoArea {
  '@type': 'Country' | 'AdministrativeArea' | 'City';
  name: string;
  containsPlace?: SchemaGeoArea[];
}

export const CHINA_AREA_SERVED: SchemaGeoArea = {
  '@type': 'Country',
  name: '中国',
  containsPlace: [
    {
      '@type': 'AdministrativeArea',
      name: '北京市',
      containsPlace: [
        {
          '@type': 'City',
          name: '北京市',
          containsPlace: [
            { '@type': 'AdministrativeArea', name: '东城区' },
            { '@type': 'AdministrativeArea', name: '西城区' },
            { '@type': 'AdministrativeArea', name: '朝阳区' },
            { '@type': 'AdministrativeArea', name: '海淀区' },
            { '@type': 'AdministrativeArea', name: '丰台区' },
            { '@type': 'AdministrativeArea', name: '石景山区' },
            { '@type': 'AdministrativeArea', name: '顺义区' },
            { '@type': 'AdministrativeArea', name: '通州区' },
          ],
        },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '天津市',
      containsPlace: [
        {
          '@type': 'City',
          name: '天津市',
          containsPlace: [
            { '@type': 'AdministrativeArea', name: '和平区' },
            { '@type': 'AdministrativeArea', name: '河东区' },
            { '@type': 'AdministrativeArea', name: '河西区' },
            { '@type': 'AdministrativeArea', name: '南开区' },
            { '@type': 'AdministrativeArea', name: '滨海新区' },
          ],
        },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '河北省',
      containsPlace: [
        { '@type': 'City', name: '石家庄市', containsPlace: [{ '@type': 'AdministrativeArea', name: '长安区' }] },
        { '@type': 'City', name: '唐山市' },
        { '@type': 'City', name: '秦皇岛市' },
        { '@type': 'City', name: '邯郸市' },
        { '@type': 'City', name: '保定市' },
        { '@type': 'City', name: '沧州市' },
        { '@type': 'City', name: '廊坊市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '山西省',
      containsPlace: [
        { '@type': 'City', name: '太原市', containsPlace: [{ '@type': 'AdministrativeArea', name: '迎泽区' }] },
        { '@type': 'City', name: '大同市' },
        { '@type': 'City', name: '阳泉市' },
        { '@type': 'City', name: '长治市' },
        { '@type': 'City', name: '晋城市' },
        { '@type': 'City', name: '朔州市' },
        { '@type': 'City', name: '晋中市' },
        { '@type': 'City', name: '运城市' },
        { '@type': 'City', name: '忻州市' },
        { '@type': 'City', name: '临汾市' },
        { '@type': 'City', name: '吕梁市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '内蒙古自治区',
      containsPlace: [
        { '@type': 'City', name: '呼和浩特市' },
        { '@type': 'City', name: '包头市' },
        { '@type': 'City', name: '乌海市' },
        { '@type': 'City', name: '赤峰市' },
        { '@type': 'City', name: '通辽市' },
        { '@type': 'City', name: '鄂尔多斯市' },
        { '@type': 'City', name: '呼伦贝尔市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '辽宁省',
      containsPlace: [
        { '@type': 'City', name: '沈阳市', containsPlace: [{ '@type': 'AdministrativeArea', name: '和平区' }] },
        { '@type': 'City', name: '大连市', containsPlace: [{ '@type': 'AdministrativeArea', name: '中山区' }] },
        { '@type': 'City', name: '鞍山市' },
        { '@type': 'City', name: '抚顺市' },
        { '@type': 'City', name: '本溪市' },
        { '@type': 'City', name: '丹东市' },
        { '@type': 'City', name: '锦州市' },
        { '@type': 'City', name: '营口市' },
        { '@type': 'City', name: '阜新市' },
        { '@type': 'City', name: '辽阳市' },
        { '@type': 'City', name: '盘锦市' },
        { '@type': 'City', name: '铁岭市' },
        { '@type': 'City', name: '朝阳市' },
        { '@type': 'City', name: '葫芦岛市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '吉林省',
      containsPlace: [
        { '@type': 'City', name: '长春市', containsPlace: [{ '@type': 'AdministrativeArea', name: '朝阳区' }] },
        { '@type': 'City', name: '吉林市' },
        { '@type': 'City', name: '四平市' },
        { '@type': 'City', name: '辽源市' },
        { '@type': 'City', name: '通化市' },
        { '@type': 'City', name: '白山市' },
        { '@type': 'City', name: '松原市' },
        { '@type': 'City', name: '白城市' },
        { '@type': 'City', name: '延边朝鲜族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '黑龙江省',
      containsPlace: [
        { '@type': 'City', name: '哈尔滨市', containsPlace: [{ '@type': 'AdministrativeArea', name: '南岗区' }] },
        { '@type': 'City', name: '齐齐哈尔市' },
        { '@type': 'City', name: '鸡西市' },
        { '@type': 'City', name: '鹤岗市' },
        { '@type': 'City', name: '双鸭山市' },
        { '@type': 'City', name: '大庆市' },
        { '@type': 'City', name: '伊春市' },
        { '@type': 'City', name: '佳木斯市' },
        { '@type': 'City', name: '七台河市' },
        { '@type': 'City', name: '牡丹江市' },
        { '@type': 'City', name: '黑河市' },
        { '@type': 'City', name: '绥化市' },
        { '@type': 'City', name: '大兴安岭地区' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '上海市',
      containsPlace: [
        {
          '@type': 'City',
          name: '上海市',
          containsPlace: [
            { '@type': 'AdministrativeArea', name: '黄浦区' },
            { '@type': 'AdministrativeArea', name: '徐汇区' },
            { '@type': 'AdministrativeArea', name: '长宁区' },
            { '@type': 'AdministrativeArea', name: '静安区' },
            { '@type': 'AdministrativeArea', name: '普陀区' },
            { '@type': 'AdministrativeArea', name: '虹口区' },
            { '@type': 'AdministrativeArea', name: '杨浦区' },
            { '@type': 'AdministrativeArea', name: '闵行区' },
            { '@type': 'AdministrativeArea', name: '宝山区' },
            { '@type': 'AdministrativeArea', name: '嘉定区' },
            { '@type': 'AdministrativeArea', name: '浦东新区' },
            { '@type': 'AdministrativeArea', name: '松江区' },
            { '@type': 'AdministrativeArea', name: '青浦区' },
            { '@type': 'AdministrativeArea', name: '奉贤区' },
            { '@type': 'AdministrativeArea', name: '崇明区' },
          ],
        },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '江苏省',
      containsPlace: [
        { '@type': 'City', name: '南京市', containsPlace: [{ '@type': 'AdministrativeArea', name: '玄武区' }, { '@type': 'AdministrativeArea', name: '建邺区' }] },
        { '@type': 'City', name: '苏州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '工业园区' }, { '@type': 'AdministrativeArea', name: '高新区' }] },
        { '@type': 'City', name: '无锡市' },
        { '@type': 'City', name: '徐州市' },
        { '@type': 'City', name: '常州市' },
        { '@type': 'City', name: '南通市' },
        { '@type': 'City', name: '连云港市' },
        { '@type': 'City', name: '淮安市' },
        { '@type': 'City', name: '盐城市' },
        { '@type': 'City', name: '扬州市' },
        { '@type': 'City', name: '镇江市' },
        { '@type': 'City', name: '泰州市' },
        { '@type': 'City', name: '宿迁市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '浙江省',
      containsPlace: [
        { '@type': 'City', name: '杭州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '西湖区' }, { '@type': 'AdministrativeArea', name: '余杭区' }] },
        { '@type': 'City', name: '宁波市', containsPlace: [{ '@type': 'AdministrativeArea', name: '鄞州区' }] },
        { '@type': 'City', name: '温州市' },
        { '@type': 'City', name: '嘉兴市' },
        { '@type': 'City', name: '湖州市' },
        { '@type': 'City', name: '绍兴市' },
        { '@type': 'City', name: '金华市' },
        { '@type': 'City', name: '衢州市' },
        { '@type': 'City', name: '舟山市' },
        { '@type': 'City', name: '台州市' },
        { '@type': 'City', name: '丽水市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '安徽省',
      containsPlace: [
        { '@type': 'City', name: '合肥市', containsPlace: [{ '@type': 'AdministrativeArea', name: '蜀山区' }, { '@type': 'AdministrativeArea', name: '包河区' }] },
        { '@type': 'City', name: '芜湖市' },
        { '@type': 'City', name: '蚌埠市' },
        { '@type': 'City', name: '淮南市' },
        { '@type': 'City', name: '马鞍山市' },
        { '@type': 'City', name: '淮北市' },
        { '@type': 'City', name: '铜陵市' },
        { '@type': 'City', name: '安庆市' },
        { '@type': 'City', name: '黄山市' },
        { '@type': 'City', name: '滁州市' },
        { '@type': 'City', name: '阜阳市' },
        { '@type': 'City', name: '宿州市' },
        { '@type': 'City', name: '六安市' },
        { '@type': 'City', name: '亳州市' },
        { '@type': 'City', name: '池州市' },
        { '@type': 'City', name: '宣城市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '福建省',
      containsPlace: [
        { '@type': 'City', name: '福州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '鼓楼区' }] },
        { '@type': 'City', name: '厦门市', containsPlace: [{ '@type': 'AdministrativeArea', name: '思明区' }] },
        { '@type': 'City', name: '莆田市' },
        { '@type': 'City', name: '三明市' },
        { '@type': 'City', name: '泉州市' },
        { '@type': 'City', name: '漳州市' },
        { '@type': 'City', name: '南平市' },
        { '@type': 'City', name: '龙岩市' },
        { '@type': 'City', name: '宁德市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '江西省',
      containsPlace: [
        { '@type': 'City', name: '南昌市', containsPlace: [{ '@type': 'AdministrativeArea', name: '东湖区' }] },
        { '@type': 'City', name: '景德镇市' },
        { '@type': 'City', name: '萍乡市' },
        { '@type': 'City', name: '九江市' },
        { '@type': 'City', name: '新余市' },
        { '@type': 'City', name: '鹰潭市' },
        { '@type': 'City', name: '赣州市' },
        { '@type': 'City', name: '吉安市' },
        { '@type': 'City', name: '宜春市' },
        { '@type': 'City', name: '抚州市' },
        { '@type': 'City', name: '上饶市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '山东省',
      containsPlace: [
        { '@type': 'City', name: '济南市', containsPlace: [{ '@type': 'AdministrativeArea', name: '历下区' }] },
        { '@type': 'City', name: '青岛市', containsPlace: [{ '@type': 'AdministrativeArea', name: '市南区' }] },
        { '@type': 'City', name: '淄博市' },
        { '@type': 'City', name: '枣庄市' },
        { '@type': 'City', name: '东营市' },
        { '@type': 'City', name: '烟台市' },
        { '@type': 'City', name: '潍坊市' },
        { '@type': 'City', name: '济宁市' },
        { '@type': 'City', name: '泰安市' },
        { '@type': 'City', name: '威海市' },
        { '@type': 'City', name: '日照市' },
        { '@type': 'City', name: '临沂市' },
        { '@type': 'City', name: '德州市' },
        { '@type': 'City', name: '聊城市' },
        { '@type': 'City', name: '滨州市' },
        { '@type': 'City', name: '菏泽市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '河南省',
      containsPlace: [
        { '@type': 'City', name: '郑州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '金水区' }] },
        { '@type': 'City', name: '开封市' },
        { '@type': 'City', name: '洛阳市' },
        { '@type': 'City', name: '平顶山市' },
        { '@type': 'City', name: '安阳市' },
        { '@type': 'City', name: '鹤壁市' },
        { '@type': 'City', name: '新乡市' },
        { '@type': 'City', name: '焦作市' },
        { '@type': 'City', name: '濮阳市' },
        { '@type': 'City', name: '许昌市' },
        { '@type': 'City', name: '漯河市' },
        { '@type': 'City', name: '三门峡市' },
        { '@type': 'City', name: '南阳市' },
        { '@type': 'City', name: '商丘市' },
        { '@type': 'City', name: '信阳市' },
        { '@type': 'City', name: '周口市' },
        { '@type': 'City', name: '驻马店市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '湖北省',
      containsPlace: [
        { '@type': 'City', name: '武汉市', containsPlace: [{ '@type': 'AdministrativeArea', name: '武昌区' }, { '@type': 'AdministrativeArea', name: '江岸区' }] },
        { '@type': 'City', name: '黄石市' },
        { '@type': 'City', name: '十堰市' },
        { '@type': 'City', name: '宜昌市' },
        { '@type': 'City', name: '襄阳市' },
        { '@type': 'City', name: '鄂州市' },
        { '@type': 'City', name: '荆门市' },
        { '@type': 'City', name: '孝感市' },
        { '@type': 'City', name: '荆州市' },
        { '@type': 'City', name: '黄冈市' },
        { '@type': 'City', name: '咸宁市' },
        { '@type': 'City', name: '随州市' },
        { '@type': 'City', name: '恩施土家族苗族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '湖南省',
      containsPlace: [
        { '@type': 'City', name: '长沙市', containsPlace: [{ '@type': 'AdministrativeArea', name: '岳麓区' }, { '@type': 'AdministrativeArea', name: '芙蓉区' }] },
        { '@type': 'City', name: '株洲市' },
        { '@type': 'City', name: '湘潭市' },
        { '@type': 'City', name: '衡阳市' },
        { '@type': 'City', name: '邵阳市' },
        { '@type': 'City', name: '岳阳市' },
        { '@type': 'City', name: '常德市' },
        { '@type': 'City', name: '张家界市' },
        { '@type': 'City', name: '益阳市' },
        { '@type': 'City', name: '郴州市' },
        { '@type': 'City', name: '永州市' },
        { '@type': 'City', name: '怀化市' },
        { '@type': 'City', name: '娄底市' },
        { '@type': 'City', name: '湘西土家族苗族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '广东省',
      containsPlace: [
        { '@type': 'City', name: '广州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '天河区' }, { '@type': 'AdministrativeArea', name: '越秀区' }] },
        { '@type': 'City', name: '深圳市', containsPlace: [{ '@type': 'AdministrativeArea', name: '南山区' }, { '@type': 'AdministrativeArea', name: '福田区' }] },
        { '@type': 'City', name: '珠海市' },
        { '@type': 'City', name: '汕头市' },
        { '@type': 'City', name: '韶关市' },
        { '@type': 'City', name: '佛山市' },
        { '@type': 'City', name: '江门市' },
        { '@type': 'City', name: '湛江市' },
        { '@type': 'City', name: '茂名市' },
        { '@type': 'City', name: '肇庆市' },
        { '@type': 'City', name: '惠州市' },
        { '@type': 'City', name: '梅州市' },
        { '@type': 'City', name: '汕尾市' },
        { '@type': 'City', name: '河源市' },
        { '@type': 'City', name: '阳江市' },
        { '@type': 'City', name: '清远市' },
        { '@type': 'City', name: '东莞市' },
        { '@type': 'City', name: '中山市' },
        { '@type': 'City', name: '潮州市' },
        { '@type': 'City', name: '揭阳市' },
        { '@type': 'City', name: '云浮市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '广西壮族自治区',
      containsPlace: [
        { '@type': 'City', name: '南宁市', containsPlace: [{ '@type': 'AdministrativeArea', name: '青秀区' }] },
        { '@type': 'City', name: '柳州市' },
        { '@type': 'City', name: '桂林市' },
        { '@type': 'City', name: '梧州市' },
        { '@type': 'City', name: '北海市' },
        { '@type': 'City', name: '防城港市' },
        { '@type': 'City', name: '钦州市' },
        { '@type': 'City', name: '贵港市' },
        { '@type': 'City', name: '玉林市' },
        { '@type': 'City', name: '百色市' },
        { '@type': 'City', name: '贺州市' },
        { '@type': 'City', name: '河池市' },
        { '@type': 'City', name: '来宾市' },
        { '@type': 'City', name: '崇左市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '海南省',
      containsPlace: [
        { '@type': 'City', name: '海口市', containsPlace: [{ '@type': 'AdministrativeArea', name: '龙华区' }] },
        { '@type': 'City', name: '三亚市' },
        { '@type': 'City', name: '三沙市' },
        { '@type': 'City', name: '儋州市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '重庆市',
      containsPlace: [
        {
          '@type': 'City',
          name: '重庆市',
          containsPlace: [
            { '@type': 'AdministrativeArea', name: '渝中区' },
            { '@type': 'AdministrativeArea', name: '江北区' },
            { '@type': 'AdministrativeArea', name: '沙坪坝区' },
            { '@type': 'AdministrativeArea', name: '九龙坡区' },
            { '@type': 'AdministrativeArea', name: '南岸区' },
            { '@type': 'AdministrativeArea', name: '渝北区' },
          ],
        },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '四川省',
      containsPlace: [
        { '@type': 'City', name: '成都市', containsPlace: [{ '@type': 'AdministrativeArea', name: '武侯区' }, { '@type': 'AdministrativeArea', name: '高新区' }] },
        { '@type': 'City', name: '自贡市' },
        { '@type': 'City', name: '攀枝花市' },
        { '@type': 'City', name: '泸州市' },
        { '@type': 'City', name: '德阳市' },
        { '@type': 'City', name: '绵阳市' },
        { '@type': 'City', name: '广元市' },
        { '@type': 'City', name: '遂宁市' },
        { '@type': 'City', name: '内江市' },
        { '@type': 'City', name: '乐山市' },
        { '@type': 'City', name: '南充市' },
        { '@type': 'City', name: '眉山市' },
        { '@type': 'City', name: '宜宾市' },
        { '@type': 'City', name: '广安市' },
        { '@type': 'City', name: '达州市' },
        { '@type': 'City', name: '雅安市' },
        { '@type': 'City', name: '巴中市' },
        { '@type': 'City', name: '资阳市' },
        { '@type': 'City', name: '阿坝藏族羌族自治州' },
        { '@type': 'City', name: '甘孜藏族自治州' },
        { '@type': 'City', name: '凉山彝族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '贵州省',
      containsPlace: [
        { '@type': 'City', name: '贵阳市', containsPlace: [{ '@type': 'AdministrativeArea', name: '南明区' }] },
        { '@type': 'City', name: '六盘水市' },
        { '@type': 'City', name: '遵义市' },
        { '@type': 'City', name: '安顺市' },
        { '@type': 'City', name: '毕节市' },
        { '@type': 'City', name: '铜仁市' },
        { '@type': 'City', name: '黔西南布依族苗族自治州' },
        { '@type': 'City', name: '黔东南苗族侗族自治州' },
        { '@type': 'City', name: '黔南布依族苗族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '云南省',
      containsPlace: [
        { '@type': 'City', name: '昆明市', containsPlace: [{ '@type': 'AdministrativeArea', name: '五华区' }] },
        { '@type': 'City', name: '曲靖市' },
        { '@type': 'City', name: '玉溪市' },
        { '@type': 'City', name: '保山市' },
        { '@type': 'City', name: '昭通市' },
        { '@type': 'City', name: '丽江市' },
        { '@type': 'City', name: '普洱市' },
        { '@type': 'City', name: '临沧市' },
        { '@type': 'City', name: '楚雄彝族自治州' },
        { '@type': 'City', name: '红河哈尼族彝族自治州' },
        { '@type': 'City', name: '文山壮族苗族自治州' },
        { '@type': 'City', name: '西双版纳傣族自治州' },
        { '@type': 'City', name: '大理白族自治州' },
        { '@type': 'City', name: '德宏傣族景颇族自治州' },
        { '@type': 'City', name: '怒江傈僳族自治州' },
        { '@type': 'City', name: '迪庆藏族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '西藏自治区',
      containsPlace: [
        { '@type': 'City', name: '拉萨市', containsPlace: [{ '@type': 'AdministrativeArea', name: '城关区' }] },
        { '@type': 'City', name: '日喀则市' },
        { '@type': 'City', name: '昌都市' },
        { '@type': 'City', name: '林芝市' },
        { '@type': 'City', name: '山南市' },
        { '@type': 'City', name: '那曲市' },
        { '@type': 'City', name: '阿里地区' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '陕西省',
      containsPlace: [
        { '@type': 'City', name: '西安市', containsPlace: [{ '@type': 'AdministrativeArea', name: '雁塔区' }] },
        { '@type': 'City', name: '铜川市' },
        { '@type': 'City', name: '宝鸡市' },
        { '@type': 'City', name: '咸阳市' },
        { '@type': 'City', name: '渭南市' },
        { '@type': 'City', name: '延安市' },
        { '@type': 'City', name: '汉中市' },
        { '@type': 'City', name: '榆林市' },
        { '@type': 'City', name: '安康市' },
        { '@type': 'City', name: '商洛市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '甘肃省',
      containsPlace: [
        { '@type': 'City', name: '兰州市', containsPlace: [{ '@type': 'AdministrativeArea', name: '城关区' }] },
        { '@type': 'City', name: '嘉峪关市' },
        { '@type': 'City', name: '金昌市' },
        { '@type': 'City', name: '白银市' },
        { '@type': 'City', name: '天水市' },
        { '@type': 'City', name: '武威市' },
        { '@type': 'City', name: '张掖市' },
        { '@type': 'City', name: '平凉市' },
        { '@type': 'City', name: '酒泉市' },
        { '@type': 'City', name: '庆阳市' },
        { '@type': 'City', name: '定西市' },
        { '@type': 'City', name: '陇南市' },
        { '@type': 'City', name: '临夏回族自治州' },
        { '@type': 'City', name: '甘南藏族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '青海省',
      containsPlace: [
        { '@type': 'City', name: '西宁市', containsPlace: [{ '@type': 'AdministrativeArea', name: '城中区' }] },
        { '@type': 'City', name: '海东市' },
        { '@type': 'City', name: '海北藏族自治州' },
        { '@type': 'City', name: '黄南藏族自治州' },
        { '@type': 'City', name: '海南藏族自治州' },
        { '@type': 'City', name: '果洛藏族自治州' },
        { '@type': 'City', name: '玉树藏族自治州' },
        { '@type': 'City', name: '海西蒙古族藏族自治州' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '宁夏回族自治区',
      containsPlace: [
        { '@type': 'City', name: '银川市', containsPlace: [{ '@type': 'AdministrativeArea', name: '金凤区' }] },
        { '@type': 'City', name: '石嘴山市' },
        { '@type': 'City', name: '吴忠市' },
        { '@type': 'City', name: '固原市' },
        { '@type': 'City', name: '中卫市' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '新疆维吾尔自治区',
      containsPlace: [
        { '@type': 'City', name: '乌鲁木齐市', containsPlace: [{ '@type': 'AdministrativeArea', name: '天山区' }] },
        { '@type': 'City', name: '克拉玛依市' },
        { '@type': 'City', name: '吐鲁番市' },
        { '@type': 'City', name: '哈密市' },
        { '@type': 'City', name: '昌吉回族自治州' },
        { '@type': 'City', name: '博尔塔拉蒙古自治州' },
        { '@type': 'City', name: '巴音郭楞蒙古自治州' },
        { '@type': 'City', name: '阿克苏地区' },
        { '@type': 'City', name: '克孜勒苏柯尔克孜自治州' },
        { '@type': 'City', name: '喀什地区' },
        { '@type': 'City', name: '和田地区' },
        { '@type': 'City', name: '伊犁哈萨克自治州' },
        { '@type': 'City', name: '塔城地区' },
        { '@type': 'City', name: '阿勒泰地区' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '香港特别行政区',
      containsPlace: [
        { '@type': 'City', name: '中西区' },
        { '@type': 'City', name: '湾仔区' },
        { '@type': 'City', name: '东区' },
        { '@type': 'City', name: '南区' },
        { '@type': 'City', name: '油尖旺区' },
        { '@type': 'City', name: '九龙城区' },
        { '@type': 'City', name: '观塘区' },
        { '@type': 'City', name: '沙田区' },
        { '@type': 'City', name: '葵青区' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '澳门特别行政区',
      containsPlace: [
        { '@type': 'City', name: '花地玛堂区' },
        { '@type': 'City', name: '圣安多尼堂区' },
        { '@type': 'City', name: '大堂区' },
        { '@type': 'City', name: '望德堂区' },
        { '@type': 'City', name: '风顺堂区' },
        { '@type': 'City', name: '嘉模堂区' },
      ],
    },
    {
      '@type': 'AdministrativeArea',
      name: '台湾省',
      containsPlace: [
        { '@type': 'City', name: '台北市' },
        { '@type': 'City', name: '新北市' },
        { '@type': 'City', name: '桃园市' },
        { '@type': 'City', name: '台中市' },
        { '@type': 'City', name: '台南市' },
        { '@type': 'City', name: '高雄市' },
      ],
    },
  ],
};
